// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Content for Article documents
 */
interface ArticleDocumentData {
  /**
   * Title field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Article title
   * - **API ID Path**: article.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Excerpt field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Short summary used in lists/cards
   * - **API ID Path**: article.excerpt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  excerpt: prismic.KeyTextField;

  /**
   * Featured image field in *Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Publish date field in *Article*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: article.publish_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  publish_date: prismic.DateField;

  /**
   * Author field in *Article*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: article.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  author: prismic.ContentRelationshipField<"author">;

  /**
   * Categoría field in *Article*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: article.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  category: prismic.ContentRelationshipField<"category">;

  /**
   * Body field in *Article*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article.body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField; /**
   * Meta Title field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: article.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: article.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Article document from Prismic
 *
 * - **API ID**: `article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ArticleDocumentData>,
    "article",
    Lang
  >;

type ArticleIndexDocumentDataSlicesSlice = HeroSlice | IntroSlice | CtaSlice;

/**
 * Content for Artículos (Index) documents
 */
interface ArticleIndexDocumentData {
  /**
   * Slice Zone field in *Artículos (Index)*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: article_index.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ArticleIndexDocumentDataSlicesSlice>; /**
   * Meta Title field in *Artículos (Index)*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: article_index.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Artículos (Index)*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: article_index.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Artículos (Index)*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article_index.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Artículos (Index) document from Prismic
 *
 * - **API ID**: `article_index`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticleIndexDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ArticleIndexDocumentData>,
    "article_index",
    Lang
  >;

/**
 * Content for Author documents
 */
interface AuthorDocumentData {
  /**
   * Name field in *Author*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Author name
   * - **API ID Path**: author.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Avatar field in *Author*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: author.avatar
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  avatar: prismic.ImageField<never>;
}

/**
 * Author document from Prismic
 *
 * - **API ID**: `author`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AuthorDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<AuthorDocumentData>, "author", Lang>;

/**
 * Content for Categoría documents
 */
interface CategoryDocumentData {
  /**
   * Nombre field in *Categoría*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Ciudadanías
   * - **API ID Path**: category.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;
}

/**
 * Categoría document from Prismic
 *
 * - **API ID**: `category`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CategoryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CategoryDocumentData>,
    "category",
    Lang
  >;

/**
 * Item in *DetalleContacto → Detalle de contacto*
 */
export interface DetallecontactoDocumentDataDetalleDeContactoItem {
  /**
   * Tipo field in *DetalleContacto → Detalle de contacto*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: detallecontacto.detalle_de_contacto[].tipo
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  tipo: prismic.SelectField<"Email" | "Whatsapp">;

  /**
   * Link label field in *DetalleContacto → Detalle de contacto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detallecontacto.detalle_de_contacto[].link_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  link_label: prismic.KeyTextField;

  /**
   * Link URL field in *DetalleContacto → Detalle de contacto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detallecontacto.detalle_de_contacto[].link_url
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  link_url: prismic.KeyTextField;
}

/**
 * Content for DetalleContacto documents
 */
interface DetallecontactoDocumentData {
  /**
   * Detalle de contacto field in *DetalleContacto*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: detallecontacto.detalle_de_contacto[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  detalle_de_contacto: prismic.GroupField<
    Simplify<DetallecontactoDocumentDataDetalleDeContactoItem>
  >;
}

/**
 * DetalleContacto document from Prismic
 *
 * - **API ID**: `detallecontacto`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DetallecontactoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<DetallecontactoDocumentData>,
    "detallecontacto",
    Lang
  >;

type FooterDocumentDataSlicesSlice = FooterItemSlice;

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Name field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Slice Zone field in *Footer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<FooterDocumentDataSlicesSlice>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<FooterDocumentData>, "footer", Lang>;

type HomeDocumentDataSlicesSlice =
  | CtaSlice
  | ServicesSlice
  | IntroSlice
  | HeroSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>; /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type MenuDocumentDataSlicesSlice = MenuItemSlice;

/**
 * Content for Menu documents
 */
interface MenuDocumentData {
  /**
   * Slice Zone field in *Menu*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<MenuDocumentDataSlicesSlice>;
}

/**
 * Menu document from Prismic
 *
 * - **API ID**: `menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<MenuDocumentData>, "menu", Lang>;

type PageDocumentDataSlicesSlice =
  | ListaSlice
  | EquipoSlice
  | PasosSlice
  | IntroSlice
  | PreguntasFrecuentesSlice
  | FormularioSlice
  | CtaSlice
  | MitadMitadSlice
  | FourCardsSlice
  | HeroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Name field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Nombre de la pagina
   * - **API ID Path**: page.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes =
  | ArticleDocument
  | ArticleIndexDocument
  | AuthorDocument
  | CategoryDocument
  | DetallecontactoDocument
  | FooterDocument
  | HomeDocument
  | MenuDocument
  | PageDocument;

/**
 * Primary content in *Cta → Default → Primary*
 */
export interface CtaSliceDefaultPrimary {
  /**
   * Titulo field in *Cta → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.titulo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  titulo: prismic.KeyTextField;

  /**
   * Texto field in *Cta → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.texto
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  texto: prismic.KeyTextField;

  /**
   * Contacto field in *Cta → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.contacto
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  contacto: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary" | "Ghost"
  >;

  /**
   * Whatsapp field in *Cta → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.whatsapp
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  whatsapp: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary" | "Ghost"
  >;
}

/**
 * Default variation for Cta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Cta*
 */
type CtaSliceVariation = CtaSliceDefault;

/**
 * Cta Shared Slice
 *
 * - **API ID**: `cta`
 * - **Description**: Cta
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSlice = prismic.SharedSlice<"cta", CtaSliceVariation>;

/**
 * Item in *Equipo → Default → Primary → Miembro del equipo*
 */
export interface EquipoSliceDefaultPrimaryMiembroDelEquipoItem {
  /**
   * Imagen field in *Equipo → Default → Primary → Miembro del equipo*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: equipo.default.primary.miembro_del_equipo[].imagen
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  imagen: prismic.ImageField<never>;

  /**
   * Nombre field in *Equipo → Default → Primary → Miembro del equipo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: equipo.default.primary.miembro_del_equipo[].nombre
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  nombre: prismic.KeyTextField;

  /**
   * Especialidad field in *Equipo → Default → Primary → Miembro del equipo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: equipo.default.primary.miembro_del_equipo[].especialidad
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  especialidad: prismic.KeyTextField;

  /**
   * Descripcion field in *Equipo → Default → Primary → Miembro del equipo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: equipo.default.primary.miembro_del_equipo[].descripcion
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  descripcion: prismic.KeyTextField;
}

/**
 * Primary content in *Equipo → Default → Primary*
 */
export interface EquipoSliceDefaultPrimary {
  /**
   * Titulo field in *Equipo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: equipo.default.primary.titulo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  titulo: prismic.KeyTextField;

  /**
   * Miembro del equipo field in *Equipo → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: equipo.default.primary.miembro_del_equipo[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  miembro_del_equipo: prismic.GroupField<
    Simplify<EquipoSliceDefaultPrimaryMiembroDelEquipoItem>
  >;
}

/**
 * Default variation for Equipo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EquipoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EquipoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Equipo*
 */
type EquipoSliceVariation = EquipoSliceDefault;

/**
 * Equipo Shared Slice
 *
 * - **API ID**: `equipo`
 * - **Description**: Equipo
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EquipoSlice = prismic.SharedSlice<"equipo", EquipoSliceVariation>;

/**
 * Item in *FooterItem → Default → Primary → Links*
 */
export interface FooterItemSliceDefaultPrimaryLinksItem {
  /**
   * Link field in *FooterItem → Default → Primary → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_item.default.primary.links[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *FooterItem → Default → Primary*
 */
export interface FooterItemSliceDefaultPrimary {
  /**
   * Titulo field in *FooterItem → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_item.default.primary.titulo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  titulo: prismic.KeyTextField;

  /**
   * Links field in *FooterItem → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_item.default.primary.links[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  links: prismic.GroupField<Simplify<FooterItemSliceDefaultPrimaryLinksItem>>;
}

/**
 * Default variation for FooterItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterItemSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FooterItem*
 */
type FooterItemSliceVariation = FooterItemSliceDefault;

/**
 * FooterItem Shared Slice
 *
 * - **API ID**: `footer_item`
 * - **Description**: FooterItem
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterItemSlice = prismic.SharedSlice<
  "footer_item",
  FooterItemSliceVariation
>;

/**
 * Primary content in *Formulario → Default → Primary*
 */
export interface FormularioSliceDefaultPrimary {
  /**
   * Titulo field in *Formulario → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: formulario.default.primary.titulo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  titulo: prismic.KeyTextField;

  /**
   * Contenido field in *Formulario → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: formulario.default.primary.contenido
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  contenido: prismic.RichTextField;
}

/**
 * Default variation for Formulario Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FormularioSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FormularioSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Formulario*
 */
type FormularioSliceVariation = FormularioSliceDefault;

/**
 * Formulario Shared Slice
 *
 * - **API ID**: `formulario`
 * - **Description**: Formulario
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FormularioSlice = prismic.SharedSlice<
  "formulario",
  FormularioSliceVariation
>;

/**
 * Item in *FourCards → Default → Primary → Cards*
 */
export interface FourCardsSliceDefaultPrimaryCardsItem {
  /**
   * Titulo field in *FourCards → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: four_cards.default.primary.cards[].titulo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  titulo: prismic.KeyTextField;

  /**
   * Texto field in *FourCards → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: four_cards.default.primary.cards[].texto
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  texto: prismic.KeyTextField;

  /**
   * Link field in *FourCards → Default → Primary → Cards*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: four_cards.default.primary.cards[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *FourCards → Default → Primary*
 */
export interface FourCardsSliceDefaultPrimary {
  /**
   * Titulo field in *FourCards → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: four_cards.default.primary.titulo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  titulo: prismic.KeyTextField;

  /**
   * Cards field in *FourCards → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: four_cards.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<Simplify<FourCardsSliceDefaultPrimaryCardsItem>>;
}

/**
 * Default variation for FourCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FourCardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FourCardsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FourCards*
 */
type FourCardsSliceVariation = FourCardsSliceDefault;

/**
 * FourCards Shared Slice
 *
 * - **API ID**: `four_cards`
 * - **Description**: FourCards
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FourCardsSlice = prismic.SharedSlice<
  "four_cards",
  FourCardsSliceVariation
>;

/**
 * Item in *Hero → Default → Primary → Enumeracion*
 */
export interface HeroSliceDefaultPrimaryEnumeracionItem {
  /**
   * Texto field in *Hero → Default → Primary → Enumeracion*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.enumeracion[].texto
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  texto: prismic.KeyTextField;
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Titulo field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titulo
   * - **API ID Path**: hero.default.primary.titulo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  titulo: prismic.KeyTextField;

  /**
   * Subtitulo field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.subtitulo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitulo: prismic.KeyTextField;

  /**
   * Mostrar boton contacto field in *Hero → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero.default.primary.mostrar_boton_contacto
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  mostrar_boton_contacto: prismic.BooleanField;

  /**
   * Mostrar boton WhatsApp field in *Hero → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero.default.primary.mostrar_boton_calendario
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  mostrar_boton_calendario: prismic.BooleanField;

  /**
   * Background image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Enumeracion field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.enumeracion[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  enumeracion: prismic.GroupField<
    Simplify<HeroSliceDefaultPrimaryEnumeracionItem>
  >;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero → Impacto medio → Primary*
 */
export interface HeroSliceImpactoMedioPrimary {
  /**
   * Titulo field in *Hero → Impacto medio → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titulo
   * - **API ID Path**: hero.impactoMedio.primary.titulo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  titulo: prismic.KeyTextField;

  /**
   * Subtitulo field in *Hero → Impacto medio → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.impactoMedio.primary.subtitulo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitulo: prismic.KeyTextField;

  /**
   * Background image field in *Hero → Impacto medio → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.impactoMedio.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Impacto medio variation for Hero Slice
 *
 * - **API ID**: `impactoMedio`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceImpactoMedio = prismic.SharedSliceVariation<
  "impactoMedio",
  Simplify<HeroSliceImpactoMedioPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceImpactoMedio;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *Intro → Default → Primary → Enumeracion*
 */
export interface IntroSliceDefaultPrimaryEnumeracionItem {
  /**
   * Titulo field in *Intro → Default → Primary → Enumeracion*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro.default.primary.enumeracion[].titulo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  titulo: prismic.KeyTextField;

  /**
   * Texto field in *Intro → Default → Primary → Enumeracion*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro.default.primary.enumeracion[].texto
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  texto: prismic.KeyTextField;
}

/**
 * Primary content in *Intro → Default → Primary*
 */
export interface IntroSliceDefaultPrimary {
  /**
   * Titulo field in *Intro → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro.default.primary.titulo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  titulo: prismic.KeyTextField;

  /**
   * Texto field in *Intro → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro.default.primary.texto
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  texto: prismic.KeyTextField;

  /**
   * Alinear al centro field in *Intro → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: intro.default.primary.alinear_al_centro
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  alinear_al_centro: prismic.BooleanField;

  /**
   * Enumeracion field in *Intro → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: intro.default.primary.enumeracion[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  enumeracion: prismic.GroupField<
    Simplify<IntroSliceDefaultPrimaryEnumeracionItem>
  >;

  /**
   * Imagen field in *Intro → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: intro.default.primary.imagen
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  imagen: prismic.ImageField<never>;
}

/**
 * Default variation for Intro Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IntroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IntroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Intro*
 */
type IntroSliceVariation = IntroSliceDefault;

/**
 * Intro Shared Slice
 *
 * - **API ID**: `intro`
 * - **Description**: Intro
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IntroSlice = prismic.SharedSlice<"intro", IntroSliceVariation>;

/**
 * Item in *Lista → Default → Primary → Lista*
 */
export interface ListaSliceDefaultPrimaryListaItem {
  /**
   * Texto field in *Lista → Default → Primary → Lista*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lista.default.primary.lista[].texto
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  texto: prismic.KeyTextField;
}

/**
 * Primary content in *Lista → Default → Primary*
 */
export interface ListaSliceDefaultPrimary {
  /**
   * Titulo field in *Lista → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lista.default.primary.titulo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  titulo: prismic.KeyTextField;

  /**
   * Lista field in *Lista → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: lista.default.primary.lista[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  lista: prismic.GroupField<Simplify<ListaSliceDefaultPrimaryListaItem>>;
}

/**
 * Default variation for Lista Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ListaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ListaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Lista*
 */
type ListaSliceVariation = ListaSliceDefault;

/**
 * Lista Shared Slice
 *
 * - **API ID**: `lista`
 * - **Description**: Lista
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ListaSlice = prismic.SharedSlice<"lista", ListaSliceVariation>;

/**
 * Item in *MenuItem → Default → Primary → Links*
 */
export interface MenuItemSliceDefaultPrimaryLinksItem {
  /**
   * Link field in *MenuItem → Default → Primary → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.default.primary.links[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *MenuItem → Default → Primary*
 */
export interface MenuItemSliceDefaultPrimary {
  /**
   * Links field in *MenuItem → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.default.primary.links[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  links: prismic.GroupField<Simplify<MenuItemSliceDefaultPrimaryLinksItem>>;
}

/**
 * Default variation for MenuItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MenuItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MenuItemSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MenuItem*
 */
type MenuItemSliceVariation = MenuItemSliceDefault;

/**
 * MenuItem Shared Slice
 *
 * - **API ID**: `menu_item`
 * - **Description**: MenuItem
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MenuItemSlice = prismic.SharedSlice<
  "menu_item",
  MenuItemSliceVariation
>;

/**
 * Item in *MitadMitad → Default → Primary → Cards*
 */
export interface MitadMitadSliceDefaultPrimaryCardsItem {
  /**
   * Imagen primera field in *MitadMitad → Default → Primary → Cards*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: mitad_mitad.default.primary.cards[].imagen_primera
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  imagen_primera: prismic.BooleanField;

  /**
   * Background image field in *MitadMitad → Default → Primary → Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: mitad_mitad.default.primary.cards[].background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Titulo field in *MitadMitad → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mitad_mitad.default.primary.cards[].titulo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  titulo: prismic.KeyTextField;

  /**
   * Intro field in *MitadMitad → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mitad_mitad.default.primary.cards[].intro
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  intro: prismic.KeyTextField;

  /**
   * Titulo sección field in *MitadMitad → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mitad_mitad.default.primary.cards[].titulo_seccion
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  titulo_seccion: prismic.KeyTextField;

  /**
   * Enumeracion field in *MitadMitad → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mitad_mitad.default.primary.cards[].enumeracion
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  enumeracion: prismic.RichTextField;

  /**
   * Titulo segunda sección field in *MitadMitad → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mitad_mitad.default.primary.cards[].titulo_segunda_seccion
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  titulo_segunda_seccion: prismic.KeyTextField;

  /**
   * Segunda enumeracion field in *MitadMitad → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mitad_mitad.default.primary.cards[].segunda_enumeracion
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  segunda_enumeracion: prismic.RichTextField;
}

/**
 * Primary content in *MitadMitad → Default → Primary*
 */
export interface MitadMitadSliceDefaultPrimary {
  /**
   * Titulo field in *MitadMitad → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mitad_mitad.default.primary.titulo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  titulo: prismic.KeyTextField;

  /**
   * Subtitulo field in *MitadMitad → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mitad_mitad.default.primary.subtitulo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitulo: prismic.KeyTextField;

  /**
   * Cards field in *MitadMitad → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: mitad_mitad.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<Simplify<MitadMitadSliceDefaultPrimaryCardsItem>>;
}

/**
 * Default variation for MitadMitad Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MitadMitadSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MitadMitadSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MitadMitad*
 */
type MitadMitadSliceVariation = MitadMitadSliceDefault;

/**
 * MitadMitad Shared Slice
 *
 * - **API ID**: `mitad_mitad`
 * - **Description**: MitadMitad
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MitadMitadSlice = prismic.SharedSlice<
  "mitad_mitad",
  MitadMitadSliceVariation
>;

/**
 * Item in *Pasos → Default → Primary → Pasos*
 */
export interface PasosSliceDefaultPrimaryPasosItem {
  /**
   * Paso field in *Pasos → Default → Primary → Pasos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pasos.default.primary.pasos[].paso
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  paso: prismic.KeyTextField;

  /**
   * Descripcion del paso field in *Pasos → Default → Primary → Pasos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pasos.default.primary.pasos[].descripcion_del_paso
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  descripcion_del_paso: prismic.KeyTextField;
}

/**
 * Primary content in *Pasos → Default → Primary*
 */
export interface PasosSliceDefaultPrimary {
  /**
   * Titulo field in *Pasos → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pasos.default.primary.titulo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  titulo: prismic.KeyTextField;

  /**
   * Pasos field in *Pasos → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: pasos.default.primary.pasos[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  pasos: prismic.GroupField<Simplify<PasosSliceDefaultPrimaryPasosItem>>;
}

/**
 * Default variation for Pasos Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PasosSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PasosSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Pasos*
 */
type PasosSliceVariation = PasosSliceDefault;

/**
 * Pasos Shared Slice
 *
 * - **API ID**: `pasos`
 * - **Description**: Pasos
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PasosSlice = prismic.SharedSlice<"pasos", PasosSliceVariation>;

/**
 * Item in *PreguntasFrecuentes → Default → Primary → Preguntas frecuentes*
 */
export interface PreguntasFrecuentesSliceDefaultPrimaryPreguntasFrecuentesItem {
  /**
   * Pregunta field in *PreguntasFrecuentes → Default → Primary → Preguntas frecuentes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: preguntas_frecuentes.default.primary.preguntas_frecuentes[].pregunta
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  pregunta: prismic.KeyTextField;

  /**
   * Respuesta field in *PreguntasFrecuentes → Default → Primary → Preguntas frecuentes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: preguntas_frecuentes.default.primary.preguntas_frecuentes[].respuesta
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  respuesta: prismic.KeyTextField;
}

/**
 * Primary content in *PreguntasFrecuentes → Default → Primary*
 */
export interface PreguntasFrecuentesSliceDefaultPrimary {
  /**
   * Titulo field in *PreguntasFrecuentes → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: preguntas_frecuentes.default.primary.titulo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  titulo: prismic.KeyTextField;

  /**
   * Texto field in *PreguntasFrecuentes → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: preguntas_frecuentes.default.primary.texto
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  texto: prismic.KeyTextField;

  /**
   * Preguntas frecuentes field in *PreguntasFrecuentes → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: preguntas_frecuentes.default.primary.preguntas_frecuentes[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  preguntas_frecuentes: prismic.GroupField<
    Simplify<PreguntasFrecuentesSliceDefaultPrimaryPreguntasFrecuentesItem>
  >;
}

/**
 * Default variation for PreguntasFrecuentes Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PreguntasFrecuentesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PreguntasFrecuentesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PreguntasFrecuentes*
 */
type PreguntasFrecuentesSliceVariation = PreguntasFrecuentesSliceDefault;

/**
 * PreguntasFrecuentes Shared Slice
 *
 * - **API ID**: `preguntas_frecuentes`
 * - **Description**: PreguntasFrecuentes
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PreguntasFrecuentesSlice = prismic.SharedSlice<
  "preguntas_frecuentes",
  PreguntasFrecuentesSliceVariation
>;

/**
 * Item in *Services → Default → Primary → Cards*
 */
export interface ServicesSliceDefaultPrimaryCardsItem {
  /**
   * Icono field in *Services → Default → Primary → Cards*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.cards[].icono
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icono: prismic.SelectField<
    "Ciudadanias" | "Visas" | "Consulares" | "Argentina"
  >;

  /**
   * Titulo field in *Services → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.cards[].titulo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  titulo: prismic.KeyTextField;

  /**
   * Texto field in *Services → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.cards[].texto
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  texto: prismic.KeyTextField;

  /**
   * Lista field in *Services → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.cards[].lista
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  lista: prismic.RichTextField;

  /**
   * Link field in *Services → Default → Primary → Cards*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.cards[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Services → Default → Primary*
 */
export interface ServicesSliceDefaultPrimary {
  /**
   * Titulo field in *Services → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.titulo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  titulo: prismic.KeyTextField;

  /**
   * Cards field in *Services → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<Simplify<ServicesSliceDefaultPrimaryCardsItem>>;
}

/**
 * Default variation for Services Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Services*
 */
type ServicesSliceVariation = ServicesSliceDefault;

/**
 * Services Shared Slice
 *
 * - **API ID**: `services`
 * - **Description**: Services
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesSlice = prismic.SharedSlice<
  "services",
  ServicesSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ArticleDocument,
      ArticleDocumentData,
      ArticleIndexDocument,
      ArticleIndexDocumentData,
      ArticleIndexDocumentDataSlicesSlice,
      AuthorDocument,
      AuthorDocumentData,
      CategoryDocument,
      CategoryDocumentData,
      DetallecontactoDocument,
      DetallecontactoDocumentData,
      DetallecontactoDocumentDataDetalleDeContactoItem,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      MenuDocument,
      MenuDocumentData,
      MenuDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      CtaSlice,
      CtaSliceDefaultPrimary,
      CtaSliceVariation,
      CtaSliceDefault,
      EquipoSlice,
      EquipoSliceDefaultPrimaryMiembroDelEquipoItem,
      EquipoSliceDefaultPrimary,
      EquipoSliceVariation,
      EquipoSliceDefault,
      FooterItemSlice,
      FooterItemSliceDefaultPrimaryLinksItem,
      FooterItemSliceDefaultPrimary,
      FooterItemSliceVariation,
      FooterItemSliceDefault,
      FormularioSlice,
      FormularioSliceDefaultPrimary,
      FormularioSliceVariation,
      FormularioSliceDefault,
      FourCardsSlice,
      FourCardsSliceDefaultPrimaryCardsItem,
      FourCardsSliceDefaultPrimary,
      FourCardsSliceVariation,
      FourCardsSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimaryEnumeracionItem,
      HeroSliceDefaultPrimary,
      HeroSliceImpactoMedioPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceImpactoMedio,
      IntroSlice,
      IntroSliceDefaultPrimaryEnumeracionItem,
      IntroSliceDefaultPrimary,
      IntroSliceVariation,
      IntroSliceDefault,
      ListaSlice,
      ListaSliceDefaultPrimaryListaItem,
      ListaSliceDefaultPrimary,
      ListaSliceVariation,
      ListaSliceDefault,
      MenuItemSlice,
      MenuItemSliceDefaultPrimaryLinksItem,
      MenuItemSliceDefaultPrimary,
      MenuItemSliceVariation,
      MenuItemSliceDefault,
      MitadMitadSlice,
      MitadMitadSliceDefaultPrimaryCardsItem,
      MitadMitadSliceDefaultPrimary,
      MitadMitadSliceVariation,
      MitadMitadSliceDefault,
      PasosSlice,
      PasosSliceDefaultPrimaryPasosItem,
      PasosSliceDefaultPrimary,
      PasosSliceVariation,
      PasosSliceDefault,
      PreguntasFrecuentesSlice,
      PreguntasFrecuentesSliceDefaultPrimaryPreguntasFrecuentesItem,
      PreguntasFrecuentesSliceDefaultPrimary,
      PreguntasFrecuentesSliceVariation,
      PreguntasFrecuentesSliceDefault,
      ServicesSlice,
      ServicesSliceDefaultPrimaryCardsItem,
      ServicesSliceDefaultPrimary,
      ServicesSliceVariation,
      ServicesSliceDefault,
    };
  }
}
