// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type FooterDocumentDataSlicesSlice = FooterItemSlice;

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Name field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Slice Zone field in *Footer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<FooterDocumentDataSlicesSlice>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<FooterDocumentData>, "footer", Lang>;

type HomeDocumentDataSlicesSlice =
  | CtaSlice
  | ServicesSlice
  | IntroSlice
  | HeroSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>; /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type MenuDocumentDataSlicesSlice = MenuItemSlice;

/**
 * Content for Menu documents
 */
interface MenuDocumentData {
  /**
   * Slice Zone field in *Menu*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<MenuDocumentDataSlicesSlice>;
}

/**
 * Menu document from Prismic
 *
 * - **API ID**: `menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<MenuDocumentData>, "menu", Lang>;

type PageDocumentDataSlicesSlice = HeroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Name field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Nombre de la pagina
   * - **API ID Path**: page.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes =
  | FooterDocument
  | HomeDocument
  | MenuDocument
  | PageDocument;

/**
 * Primary content in *Cta → Default → Primary*
 */
export interface CtaSliceDefaultPrimary {
  /**
   * Titulo field in *Cta → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.titulo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  titulo: prismic.KeyTextField;

  /**
   * Texto field in *Cta → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.texto
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  texto: prismic.KeyTextField;

  /**
   * Contacto field in *Cta → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.contacto
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  contacto: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary" | "Ghost"
  >;

  /**
   * Whatsapp field in *Cta → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.whatsapp
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  whatsapp: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary" | "Ghost"
  >;
}

/**
 * Default variation for Cta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Cta*
 */
type CtaSliceVariation = CtaSliceDefault;

/**
 * Cta Shared Slice
 *
 * - **API ID**: `cta`
 * - **Description**: Cta
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSlice = prismic.SharedSlice<"cta", CtaSliceVariation>;

/**
 * Item in *FooterItem → Default → Primary → Links*
 */
export interface FooterItemSliceDefaultPrimaryLinksItem {
  /**
   * Link field in *FooterItem → Default → Primary → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_item.default.primary.links[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *FooterItem → Default → Primary*
 */
export interface FooterItemSliceDefaultPrimary {
  /**
   * Titulo field in *FooterItem → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_item.default.primary.titulo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  titulo: prismic.KeyTextField;

  /**
   * Links field in *FooterItem → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_item.default.primary.links[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  links: prismic.GroupField<Simplify<FooterItemSliceDefaultPrimaryLinksItem>>;
}

/**
 * Default variation for FooterItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterItemSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FooterItem*
 */
type FooterItemSliceVariation = FooterItemSliceDefault;

/**
 * FooterItem Shared Slice
 *
 * - **API ID**: `footer_item`
 * - **Description**: FooterItem
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterItemSlice = prismic.SharedSlice<
  "footer_item",
  FooterItemSliceVariation
>;

/**
 * Item in *Hero → Default → Primary → Enumeracion*
 */
export interface HeroSliceDefaultPrimaryEnumeracionItem {
  /**
   * Texto field in *Hero → Default → Primary → Enumeracion*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.enumeracion[].texto
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  texto: prismic.KeyTextField;
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Titulo field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titulo
   * - **API ID Path**: hero.default.primary.titulo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  titulo: prismic.KeyTextField;

  /**
   * Subtitulo field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.subtitulo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitulo: prismic.KeyTextField;

  /**
   * Mostrar boton contacto field in *Hero → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero.default.primary.mostrar_boton_contacto
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  mostrar_boton_contacto: prismic.BooleanField;

  /**
   * Mostrar boton calendario field in *Hero → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero.default.primary.mostrar_boton_calendario
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  mostrar_boton_calendario: prismic.BooleanField;

  /**
   * Background image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Enumeracion field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.enumeracion[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  enumeracion: prismic.GroupField<
    Simplify<HeroSliceDefaultPrimaryEnumeracionItem>
  >;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero → Impacto medio → Primary*
 */
export interface HeroSliceImpactoMedioPrimary {
  /**
   * Titulo field in *Hero → Impacto medio → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titulo
   * - **API ID Path**: hero.impactoMedio.primary.titulo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  titulo: prismic.KeyTextField;

  /**
   * Subtitulo field in *Hero → Impacto medio → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.impactoMedio.primary.subtitulo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitulo: prismic.KeyTextField;

  /**
   * Background image field in *Hero → Impacto medio → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.impactoMedio.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Impacto medio variation for Hero Slice
 *
 * - **API ID**: `impactoMedio`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceImpactoMedio = prismic.SharedSliceVariation<
  "impactoMedio",
  Simplify<HeroSliceImpactoMedioPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceImpactoMedio;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *Intro → Default → Primary → Enumeracion*
 */
export interface IntroSliceDefaultPrimaryEnumeracionItem {
  /**
   * Titulo field in *Intro → Default → Primary → Enumeracion*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro.default.primary.enumeracion[].titulo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  titulo: prismic.KeyTextField;

  /**
   * Texto field in *Intro → Default → Primary → Enumeracion*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro.default.primary.enumeracion[].texto
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  texto: prismic.KeyTextField;
}

/**
 * Primary content in *Intro → Default → Primary*
 */
export interface IntroSliceDefaultPrimary {
  /**
   * Titulo field in *Intro → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro.default.primary.titulo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  titulo: prismic.KeyTextField;

  /**
   * Texto field in *Intro → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro.default.primary.texto
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  texto: prismic.KeyTextField;

  /**
   * Enumeracion field in *Intro → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: intro.default.primary.enumeracion[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  enumeracion: prismic.GroupField<
    Simplify<IntroSliceDefaultPrimaryEnumeracionItem>
  >;

  /**
   * Imagen field in *Intro → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: intro.default.primary.imagen
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  imagen: prismic.ImageField<never>;
}

/**
 * Default variation for Intro Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IntroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IntroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Intro*
 */
type IntroSliceVariation = IntroSliceDefault;

/**
 * Intro Shared Slice
 *
 * - **API ID**: `intro`
 * - **Description**: Intro
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IntroSlice = prismic.SharedSlice<"intro", IntroSliceVariation>;

/**
 * Item in *MenuItem → Default → Primary → Links*
 */
export interface MenuItemSliceDefaultPrimaryLinksItem {
  /**
   * Link field in *MenuItem → Default → Primary → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.default.primary.links[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *MenuItem → Default → Primary*
 */
export interface MenuItemSliceDefaultPrimary {
  /**
   * Links field in *MenuItem → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.default.primary.links[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  links: prismic.GroupField<Simplify<MenuItemSliceDefaultPrimaryLinksItem>>;
}

/**
 * Default variation for MenuItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MenuItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MenuItemSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MenuItem*
 */
type MenuItemSliceVariation = MenuItemSliceDefault;

/**
 * MenuItem Shared Slice
 *
 * - **API ID**: `menu_item`
 * - **Description**: MenuItem
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MenuItemSlice = prismic.SharedSlice<
  "menu_item",
  MenuItemSliceVariation
>;

/**
 * Item in *Services → Default → Primary → Cards*
 */
export interface ServicesSliceDefaultPrimaryCardsItem {
  /**
   * Icono field in *Services → Default → Primary → Cards*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.cards[].icono
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icono: prismic.SelectField<
    "Ciudadanias" | "Visas" | "Consulares" | "Argentina"
  >;

  /**
   * Titulo field in *Services → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.cards[].titulo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  titulo: prismic.KeyTextField;

  /**
   * Texto field in *Services → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.cards[].texto
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  texto: prismic.KeyTextField;

  /**
   * Lista field in *Services → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.cards[].lista
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  lista: prismic.RichTextField;

  /**
   * Link field in *Services → Default → Primary → Cards*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.cards[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Services → Default → Primary*
 */
export interface ServicesSliceDefaultPrimary {
  /**
   * Titulo field in *Services → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.titulo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  titulo: prismic.KeyTextField;

  /**
   * Cards field in *Services → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<Simplify<ServicesSliceDefaultPrimaryCardsItem>>;
}

/**
 * Default variation for Services Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Services*
 */
type ServicesSliceVariation = ServicesSliceDefault;

/**
 * Services Shared Slice
 *
 * - **API ID**: `services`
 * - **Description**: Services
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesSlice = prismic.SharedSlice<
  "services",
  ServicesSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      MenuDocument,
      MenuDocumentData,
      MenuDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      CtaSlice,
      CtaSliceDefaultPrimary,
      CtaSliceVariation,
      CtaSliceDefault,
      FooterItemSlice,
      FooterItemSliceDefaultPrimaryLinksItem,
      FooterItemSliceDefaultPrimary,
      FooterItemSliceVariation,
      FooterItemSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimaryEnumeracionItem,
      HeroSliceDefaultPrimary,
      HeroSliceImpactoMedioPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceImpactoMedio,
      IntroSlice,
      IntroSliceDefaultPrimaryEnumeracionItem,
      IntroSliceDefaultPrimary,
      IntroSliceVariation,
      IntroSliceDefault,
      MenuItemSlice,
      MenuItemSliceDefaultPrimaryLinksItem,
      MenuItemSliceDefaultPrimary,
      MenuItemSliceVariation,
      MenuItemSliceDefault,
      ServicesSlice,
      ServicesSliceDefaultPrimaryCardsItem,
      ServicesSliceDefaultPrimary,
      ServicesSliceVariation,
      ServicesSliceDefault,
    };
  }
}
